### ISSUE TITLE
Copyright clarification

### ISSUE THREAD

**Issue by gitterdude** [reales/OB-Xd#1]
Which of the files or folder contents  (names listed below) that used to be distributed here in the Documents/discoDSP folder do you claim copyright on and which can be used by forks of this current project?

Also, am I expected to pay you if I compile the GPL files in this current project and use the resulting binary to make sounds in a commercial product or do I only have to pay if I use your binaries?

./MIDI/Arturia MicroFreak.xml
./MIDI/Config.xml
./MIDI/Custom.xml
./MIDI/Dave Smith Instruments OB-6.xml
./MIDI/Default.xml
./MIDI/Elektron Analog Four MKII.xml
./MIDI/Elektron Digitakt.xml
./MIDI/Elektron Digitone.xml
./MIDI/IK Multimedia Uno Synth.xml
./MIDI/KORG MS2000.xml
./MIDI/KORG micro KORG.xml
./MIDI/KORG minilogue xd.xml
./MIDI/KORG minilogue.xml
./MIDI/KORG monologue.xml
./MIDI/Modal Craft.xml
./MIDI/Modal Skulpt.xml
./MIDI/Moog Minitaur.xml
./MIDI/Moog Sirin.xml
./MIDI/Moog Sub 37.xml
./MIDI/Moog Sub Phatty.xml
./MIDI/Mutable Instruments Shruthi.xml
./MIDI/Novation Circuit.xml
./MIDI/Roland JD-XA.xml
./MIDI/Roland JD-Xi.xml
./MIDI/Roland JP-08.xml
./MIDI/Roland JU-06.xml
./MIDI/Roland JX-03.xml
./MIDI/Roland SE-02.xml
./MIDI/Roland SH-01A.xml
./MIDI/Roland System-8.xml
./MIDI/Studiologic Sledge.xml
./MIDI/Tasty Chips GR-1.xml
./MIDI/Waldorf Blofeld.xml
./MIDI/freds-lab buzzzy.xml

./Themes/discoDSP Classic/*
./Themes/Ilkka Rosma Dark/*
./Themes/Rin Elyran Classic SEM/*
./Themes/discoDSP Grey/*
./Themes/discoDSP Blue/*

./Banks/000 - FMR OB-Xa Patch Book.fxb
./Banks/001 - J3PO Factory.FXB
./Banks/002 - KVR Bass.fxb
./Banks/003 - KVR Brass + Synths.fxb
./Banks/004 - KVR Drums + Percussion + SFXs.fxb
./Banks/005 - KVR Keys + Bells + Plucked.fxb
./Banks/006 - KVR Leads.fxb
./Banks/007 - KVR Pads + Strings + Vocalic.fxb
./Banks/008 - ABS Custom Shop v1.fxb
./Banks/009 - Breeze Meat-n-Potatoes.fxb
./Banks/010 - Breeze Meat-n-Potatoes Extras.fxb
./Banks/011 - IW Bank 1.fxb
./Banks/012 - Kujashi.fxb
./Banks/013 - KVR Community Bank - Part 1.fxb
./Banks/014 - KVR Community Bank - Part 2.fxb
./Banks/015 - Rin Elyran Bank.fxb
./Banks/016 - Xenos Soundworks.fxb
./Banks/017 - Joel Obxd.FXB
./Banks/018 - TheBassProject by ThePresent.FXB
./Banks/019 - Phace.FXB
./Banks/020 - J3PO Gold Bank.fxb
./Banks/021 - Vivolator.FXB
./Banks/022 - Blank Canvas.fxb
./Banks/023 - Luke's Soundhouse 80s & Synthwave.FXB

**Comment by reales** [comment]
Read the readme.

**Comment by gitterdude** [comment]
Where can I find the post that granted you sole copyright on, for instance, the KVR Community Banks; which the README implies?

Regarding a bug in Rin Elyran's Classic SEM skin you said in a KVR post on May 10, 2020 "Yeah, not my skin so I can't fix that". 
When was that copyright transferred to you and is there a public record of that?

**Comment by reales** [comment]
Rin Elyran's Classic SEM skin was redesigned from scratch by discoDSP to support OB-Xd 2.x GUI resizing and retina HiDPI. The reply you're referring to was from a skin that's not even from your property.

FXB banks don't retain any copyright to discoDSP and they were imported and adapted from the original format to work with discoDSP OB-Xd.

You're not the original author of anything you're claiming and you're distributing our copyrighted content without permission. I'd recommend to solve that situation instead.

https://github.com/gitterdude/DISTRHO-Ports/tree/master/ports/obxd/source/Images
https://github.com/gitterdude/DISTRHO-Ports/blob/master/ports/obxd/source/Gui/BinaryData.cpp

**Comment by gitterdude** [comment]
I've never said anything above is my property or that I am the original author of anything, other than the fixes and compile instructions I posted on this github channel before you deleted it all.

I have no problem removing the DISTRHO-Ports repository I cloned from falkTX 3 years ago, when the files in question supposedly _were_ under a free-to-use-and-distribute license.
I didn't even remember cloning it and it was only done to send a PR for some bugfixes I made.

You should discuss any copyright issue with falkTX and all the other 37 people who cloned his DISTRHO-Ports repository.

So am I correct in understanding that you don't claim any copyright to the FXB banks and that they are OK to redistribute as far as you know?

What about the MIDI files?

**Comment by reales** [comment]
> I've never said anything above is my property or that I am the original author of anything, other than the fixes and compile instructions I posted on this github channel before you deleted it all.
> 
I don't know what you are talking about. If it's regarding LV2 it's already fixed on the current project commit. Deletion was due to a conflict with pull request holding unwanted data on the archive and it's nothing personal against you.
> I have no problem removing the DISTRHO-Ports repository I forked from falkTX 3 years ago, when the files in question supposedly _were_ under a free-to-use-and-distribute license. I didn't even remember cloning it and it was only done to send a PR for some bugfixes I made.
> 
Again... they never were. There isn't any PR with your name either from any previous OB-Xd projects, only three contributor who have been already paid by me and another from a coder I had to sort out some private issue.
> You should discuss any copyright issue with falkTX and all the other 37 people who forked his DISTRHO-Ports repository on Github. Not to mention all the linux distros who may also have cloned it and have it in _their_ public repositories.
> 
They're already aware of this and I'm sure it's being addressed.
> So am I correct in understanding that you don't claim any copyright to the FXB banks and that they are OK to redistribute as far as you know?
> 
Even if I adapted the original ones I can't claim anything because those kind of synth presets are not protected by copyright.
> What about the MIDI files?
Same. I paid a freelancer to make those MIDI XML boards but they are presets. If you want to take advantage of them on another distribution I have to nothing to do about that.

Once you acknowledge that you understood everything I'll proceeded to delete this issue because it's not related to the project source code and should have been discussed privately.

**Comment by gitterdude** [comment]
You said _The reply you're referring to was from a skin that's not even from your property_ and _You're not the original author of anything you're claiming_  
I just pointed out that I wasn't claiming to be the author of _anything_ in my initial two posts.

I also never said I contributed to OB-Xd; please read what I write.
I forked falkTX's DISTRHO-Ports to fix a few things in that project and posted PR's to _him_ , since he's the owner of that repo.

Good to know that it's OK to reuse the banks and MIDI files.

I think this discussion _is_ in a way related to the source code since I'm sure lots of people have forked or cloned this repo before it was deleted and fundamentally changed.

The README statement that "Other images and **applicable resources** have all rights reserved and copyrighted to discoDSP" does suggest that the Banks and MIDI files could very well be such "applicable resources".
After all you did just claim that a JUCE generated file containing almost nothing but numbers were infringing on your copyright, so it's not entirely clear from a non-lawyer POV which files are copyright and which aren't.

So if you delete this conversation you should at least make it clear in the README that your copyright doesn't extend to the Banks and MIDI files previously here and which, I presume, are also available in the binary download.
