### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by jips63** [reales/OB-Xd#1]
Since the version 1.3, it's no more possible to use the "<" and ">" buttons in Logic to browse (by increment) the presets. I'm using aupresets, in folders (with categories : Bass, Bells, Pads, etc.), and it worked perfectly in the 0.2.0 version.

It's fine to have access to different banks (since the 1.4), but it's fine to have a custom selection of presets.

**Comment by reales** [comment]
Tried with Logic 10.4.1 without problems. Make sure presets are located at /Library/Audio/Presets/Datsounds/OB-Xd
