### ISSUE TITLE
multiple definition of `juce_CreateApplication()

### ISSUE THREAD

**Issue by KottV** [reales/OB-Xd#12]
Hi,

With recent changes compilation fails on final linking:

>/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: build/Obxd64.a(PluginEditor_94d4fb09.o): in function `juce_CreateApplication()':
PluginEditor.cpp:(.text+0x1830): multiple definition of `juce_CreateApplication()'; build/Obxd64.a(StandaloneFilterApp_e433cd25.o):StandaloneFilterApp.cpp:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status

**Comment by reales** [comment]
Thanks for the report. Will revert changes.
