### ISSUE TITLE
Issue with automation in Cakewalk

### ISSUE THREAD

**Issue by erjadi** [reales/OB-Xd#13]
Hi, this might be a very specific use case but I decided to file this anyway.
Midi Learn and automation work flawlessly in the standalone version, but in my DAW (Cakewalk by Bandlab) it doesn't work for all parameters.

Cakewalk uses something called ACT to enumerate all VST parameters, and this should allow the DAW to link input control messages to each parameter. The curious thing is that it works for some parameters (volume, master pitch) but not for others (cutoff / resonance). I can see from the setup screen already that volume is accurately reflected (real-time) in both the DAW and the synth UI, but cutoff for example doesn't.

Not having looked at the code yet, but is there a different way that volume is handled as opposed to e.g. cutoff?

I can upload a little video to make things clearer, will take a look at the code myself later.

**Comment by erjadi** [comment]
P.S. Automation works for all other VSTs I have and I've tested and observed this issue with the VST and VST3 versions of OB-Xd.

**Comment by reales** [comment]
Parameter code has been refactored recently and it shouldn't happen. Are you talking about 1.5 binary or the latest 2.0 from compiled from source?

**Comment by erjadi** [comment]
Ah that's an excellent point, I'm just using the 1.5 binary now. Are there any build instructions in the project? I'm not so familiar with Juce but I couldn't get it to build. Is there a specific version of the Juce modules that this project depends on?

**Comment by reales** [comment]
Just updated [Readme.md](https://github.com/reales/OB-Xd/blob/master/README.md) with Nightly builds and building instructions.
Please report back if issue persist in nightly.

**Comment by erjadi** [comment]
Hi thanks for the instructions and indeed the nightly build works flawlessly! Thanks so much!
