### ISSUE TITLE
Menu offset

### ISSUE THREAD

**Issue by biopsin** [reales/OB-Xd#14]
Hi, first like to say thank you for continuing working on this.
I have a minor issue regarding the right click menu being way off instead of below pointer. This started occuring in v1.5

![20-04-25--1587815533_scrot](https://user-images.githubusercontent.com/60029989/80279277-cbf60500-86fc-11ea-861b-669a3a072b8a.png)

**Comment by reales** [comment]
v2.0 should be out soon with the issue fixed.
