### ISSUE TITLE
Missed declaration of scanAndUpdateSkins()

### ISSUE THREAD

**Issue by KottV** [reales/OB-Xd#16]
Hi,

with latest commit b26face84b35036181b400510f05197cff77925c build fails due undeclared scanAndUpdateSkins and it's members:

> ../../Source/PluginEditor.cpp:22:24: error: ‘class ObxdAudioProcessor’ has no member named ‘getSkinFiles’; did you mean ‘getSkinFolder’?
   22 |       skins (processor.getSkinFiles()),
      |                        ^~~~~~~~~~~~
      |                        getSkinFolder
../../Source/PluginEditor.cpp: In member function ‘void ObxdAudioProcessorEditor::loadSkin(ObxdAudioProcessor&)’:
../../Source/PluginEditor.cpp:49:46: error: cannot convert ‘std::unique_ptr<juce::XmlElement>’ to ‘juce::XmlElement*’ in initialization
   49 |     XmlElement* doc = skin.getDocumentElement();
      |                       ~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                              |
      |                                              std::unique_ptr<juce::XmlElement>
../../Source/PluginEditor.cpp: In member function ‘void ObxdAudioProcessorEditor::createMenu()’:
../../Source/PluginEditor.cpp:318:23: error: ‘class ObxdAudioProcessor’ has no member named ‘getSkinFiles’; did you mean ‘getSkinFolder’?
  318 |     skins = processor.getSkinFiles();
      |                       ^~~~~~~~~~~~
      |                       getSkinFolder
../../Source/PluginProcessor.cpp: In constructor ‘ObxdAudioProcessor::ObxdAudioProcessor()’:
../../Source/PluginProcessor.cpp:80:5: error: ‘scanAndUpdateSkins’ was not declared in this scope; did you mean ‘scanAndUpdateBanks’?
   80 |     scanAndUpdateSkins();
      |     ^~~~~~~~~~~~~~~~~~
      |     scanAndUpdateBanks
../../Source/PluginProcessor.cpp: At global scope:
../../Source/PluginProcessor.cpp:591:6: error: no declaration matches ‘void ObxdAudioProcessor::scanAndUpdateSkins()’
  591 | void ObxdAudioProcessor::scanAndUpdateSkins()
      |      ^~~~~~~~~~~~~~~~~~
../../Source/PluginProcessor.cpp:591:6: note: no functions named ‘void ObxdAudioProcessor::scanAndUpdateSkins()’
In file included from ../../Source/PluginProcessor.cpp:10:
../../Source/PluginProcessor.h:116:7: note: ‘class ObxdAudioProcessor’ defined here
  116 | class ObxdAudioProcessor  : public AudioProcessor,
      |       ^~~~~~~~~~~~~~~~~~
../../Source/PluginProcessor.cpp:608:20: error: no declaration matches ‘const juce::Array<juce::File>& ObxdAudioProcessor::getSkinFiles() const’
  608 | const Array<File>& ObxdAudioProcessor::getSkinFiles() const
      |                    ^~~~~~~~~~~~~~~~~~
../../Source/PluginProcessor.cpp:608:20: note: no functions named ‘const juce::Array<juce::File>& ObxdAudioProcessor::getSkinFiles() const’
In file included from ../../Source/PluginProcessor.cpp:10:
../../Source/PluginProcessor.h:116:7: note: ‘class ObxdAudioProcessor’ defined here
  116 | class ObxdAudioProcessor  : public AudioProcessor,

**Comment by reales** [comment]
What's the JUCE release used for compiling?

**Comment by KottV** [comment]
What's the JUCE release used for compiling?

> 5.4.7

**Comment by reales** [comment]
Try using 5.4.3 as pointed at https://github.com/reales/OB-Xd#building

**Comment by KottV** [comment]
Thanks, just tried, but with the same result. I can't see scanAndUpdateSkins in PluginProcessor.h
Maybe it just was not pushed? :)

**Comment by reales** [comment]
Pushed now.

**Comment by KottV** [comment]
All good. Thank You!
