### ISSUE TITLE
VST2 is deprecated; VST3 builds don't work

### ISSUE THREAD

**Issue by Skrylar** [reales/OB-Xd#17]
It is no longer possible to perform VST2 builds for the general public as Steinberg has been going around scorching the SDK from the internet. However turning on VST3 support without VST1/2 support in Projucer results in makefiles that build a standalone version and no plugins.

**Comment by reales** [comment]
Builds just fine here with VST2 SDK removed and VST legacy off.

**Comment by Skrylar** [comment]
Well it may be “closed,” but it’s not building anything other than the
standalone on my machine :shrugs:

Will try a git reset / another clone in a bit.

**Comment by Skrylar** [comment]
OB-Xd: 95b57d2c59e9d3bb47527d27d7987a8ei
OB-Xd upgraded to: 2efb25b9a9b82b84abc948a0c8f404c9afe34863

```
git clean -dfx
git clean --reset hard
<projucer, gear icon, disable all targets except VST3>
save project
save
make
<make: Nothing to be done for 'all'.>
```

Inspect Makefile and `-DJucePlugin_Build_VST3` is always set to zero even though its set to one in Projucer.

Something, somewhere, keeps disabling the build even though its turned on in the editor.

**Comment by hfiguiere** [comment]
You don't say, but if you are on Linux (given that you use `make`) there is no VST3 target since JUCE 5.x doesn't support VST3 on Linux.
