### ISSUE TITLE
MIDI Learn Clear button doesn't light up when pressed

### ISSUE THREAD

**Issue by VincyZed** [reales/OB-Xd#22]
I'm not sure if this was an intentional change because of the fact that MIDI Learn Clear is momentary instead of being a toggled state, but it could be nice if it would momentarily light up when the button is pressed, and turn back off when letting go of the left mouse button. Right now, in my opinion, the fact that it doesn't light up makes it lack visual feedback compared to the rest of the interface.

By the way, that new skin in version 2.0 is sweeeet! :)

**Comment by reales** [comment]
Fixed on https://github.com/reales/OB-Xd/commit/d283309d882fcc9a45ee685660e8ee927c64942b
