### ISSUE TITLE
OB-Xd V2 theme issues on Linux

### ISSUE THREAD

**Issue by xard-dev** [reales/OB-Xd#25]
New V2 shipped themes have scale issues due to the theme resources. I'm using 1x (I think, there's no option to change between scales). I'll list the problems by themes:

**discoDSP Classic**
Legato is not scaled properly:
![image](https://user-images.githubusercontent.com/65303522/89715289-4f3a1e80-d9ad-11ea-95e1-c553469f327b.png)

**Ilkka Rosma Dark**
Legato and Voices are not scaled properly:
![image](https://user-images.githubusercontent.com/65303522/89715314-7abd0900-d9ad-11ea-97e3-8654e8f1e16d.png)

**Rin Elyran Classic SEM**
Legato and Voices are not scaled properly:
![image](https://user-images.githubusercontent.com/65303522/89715327-9e804f00-d9ad-11ea-8ee4-18b8ed2c6c8a.png)

**discoDSP Blue**
Legato and Voices are not scaled properly:
![image](https://user-images.githubusercontent.com/65303522/89715346-c8397600-d9ad-11ea-90ed-ce928ed23c9e.png)

**discoDSP Grey**
Almost everything besides Legato, Voices and buttons:
![image](https://user-images.githubusercontent.com/65303522/89715368-f4ed8d80-d9ad-11ea-8e59-9697f19efc30.png)

**Details**
Seems like the common theme for all Legato and Voices are that they are expected to be 2x resolution or are not drawn correctly. The Grey demonstrates what happens when the theme has almost all resources at 2x size on all bitmaps which breaks most of the UI.

**Comment by reales** [comment]
2.x themes are not compatible with 1.x. Use 2.x releases for 2.x themes.

**Comment by xard-dev** [comment]
So are you shipping 2.x themes with 1.x plugin?

Both are from same package (md5sums):
```
4aef19e9b9bc359eac06a04f9507dbaf  OB-Xd.so
337635a13edd224b6fb8229d804f2b96  Obxd20Linux.zip
```
