### ISSUE TITLE
Lock MIDI Map

### ISSUE THREAD

**Issue by FunkybotsEvilTwin** [reales/OB-Xd#28]
Would be nice if there were an option to completely lock the current MIDI Map. There have been times where browsing presets, the MIDI assignment map seems to have changed. Would prefer a way to lock it globally so I can map OB-Xd to my keyboard once, and have that mapping stay in place forever going forward.

**Comment by mkruselj** [comment]
Indeed - MIDI learn setup should be either completely global for all instances, or global per instance.

**Comment by reales** [comment]
New MIDI feature fixed this for all global instances since https://github.com/reales/OB-Xd/commit/a1b851a4eb3e4feee811ea54d10446e67c3902dd
