### ISSUE TITLE
No bank loaded by default

### ISSUE THREAD

**Issue by josephernest** [reales/OB-Xd#3]
In most synthesizers VST, when launching the VST, it auto loads a default/factory soundbank.

In OBXD, it doesn't load any preset bank. It's a bit long to have to do this *each time* after loading the VST: go in the menu (see below), "load FXB", browse in your disk to search the FXB folder, find the bank, etc.

[Here](https://obxd.wordpress.com/) many many many comments are about people not finding the presets...

**Suggestion: could we auto-load a default preset bank?**

Question: which `.fxb` file should be considered as a default factory sound bank? (i.e. it contains good sounds, in a wide palette, chosen by you) (001 - Init Bank.fxb is empty, 002 - KVR Bass.fxb is only bass... which one should be the default one?)

Thank you in advance :)

![](http://gget.it/dkxki/obxd3.jpg)

**Comment by reales** [comment]
Pending for 1.5 update, thanks for the suggestion.

**Comment by josephernest** [comment]
Thank you very much, I think this would be super useful because many people have this question about OB-Xd on forums :)

1) Which bank would you recommend as default soundbank ?

(0001 is empty)

![](http://gget.it/b9nvg/1.jpg)

2) Is it possible to get the real Oberheim OB-X synthesizer (1979) default factory presets A1, ..., A8, ..., D1, ..., D8? If already available, which bank is it?

**Comment by reales** [comment]
1. I think 14 FMR OB-Xa Patch Book covers that.
2. Choice is difficult, but candidates are AZurStudio, FMR OB-Xa or KVR Community Banks.

**Comment by reales** [comment]
OB-Xd loads the first file from Banks folder. In this case it happens to be 001 - Init.fxb which contains empty programs. The simplest solution would be adding a 000 - Bank.fxb with a better collection of patches or wait for the next update with a better, more appropiate bank compilation.
