### ISSUE TITLE
Preset Selection out of sync in Logic

### ISSUE THREAD

**Issue by MPascarella** [reales/OB-Xd#31]
In Logic, there are two ways of selecting a preset - one from OB-Xd2's interface, and the other from the Logic's plugin window menu. By selecting a bank other than 000 from the OB-Xd2 interface and then a preset, you can get Logic's plugin UI and the OB-Xd2 UI to show two different selected presets.

**Comment by reales** [comment]
Using latest development build with JUCE 6 seem to sync presets properly.
