### ISSUE TITLE
Can't make VST3, VST2 dependencies?

### ISSUE THREAD

**Issue by totally-G** [reales/OB-Xd#33]
What I have done:
Downloaded and installed VS2019 and selected desktop development
Downloaded Juce 5.47 (from link),VST SDK 3 (as specified in the github readme)
Downloaded Juce 6 to be able to open the jucer file from the github source (the 5.47 did not contain Projucer)
Open Projucer and set the Juce path to the 5.47 extracted download
Open the jucer file and the open the generated wrapper file in VS2019

Building Ob-Xd shared code **OK**
Building Ob-Xd stand-alone **OK**
Building Ob-Xd VST3          **FAILS**

From what I can see is some dependencies to VST2 stuff.

#if JUCE_VST3_CAN_REPLACE_VST2
namespace Vst2
{
#include “pluginterfaces/vst2.x/vstfxstore.h”
}
#endif

Then 20+ errors related to bank that seems to have dependencies to Vst2 and fx storage?

bool loadVST2CcnKBlock (const char* data, int size)
{
    auto bank = (const Vst2::fxBank*) data; //< this gives an error
}

Thanks!

**Comment by reales** [comment]
Try using ProJucer 4.5.7 and remove any VST2 references from the project.
