### ISSUE TITLE
Crashes on macOS when Live doesn't have permission to view Documents

### ISSUE THREAD

**Issue by erwald** [reales/OB-Xd#34]
Hi there, thanks for making this.

I realised that OB-Xd crashes when following these steps:

1. Go to Software Preferences > Security & Privacy > Privacy > Files and Folders
2. Disallow Ableton Live's (may work for other DAWs, too) access to Documents Folder
3. Open Ableton Live
4. Load OB-Xd into a MIDI track
5. Live crashes instantly, without a warning

I assume it's b/c the synth needs access to the Document folder, and assumes it does have access even if the host app doesn't? Something like that.

I'm on macOS 10.15.5 with Live 9. I tried with both v2.1 and v2.0 of OB-Xd, same issue for both versions.

Cheers

**Comment by kolyasya** [comment]
@erwald wow, thank you! I just reinstalled OB-Xd and it crashed Reaper DAW the same way. Allowing access to documents folder fixed everything.

**Comment by reales** [comment]
Fixed on https://github.com/reales/OB-Xd/commit/3f32716745e85f2aa2d5a95e2764ce13cb207efd
