### ISSUE TITLE
Re-use the filters

### ISSUE THREAD

**Issue by baconpaul** [reales/OB-Xd#35]
Hi!

I'm one of the maintainers on Surge (https://surge-synthesizer.github.io/).

We are in the process of adding more filter models to Surge, perhaps. (It's still at a dev stage). Several of our users have praised the OB-Xd filters as among the best FOSS filters out there.

I know you've spoken with a few folks on our team about us using your code for bits and bobs, and you're GPL3 and we're GPL3, so sharing code is easy, but good open source projects work well with good communication. So a couple of questions

1. If we made the OB-Xd filter a new filter type in surge, any grave concerns here? From the code perspective i know how to do (thanks for writing relatively straight forward code)

2. Would you rather we name that filter with the OB-Xd name or not in the synth? Right now our filter selector looks like this and I would most likely just add "OB-Xd filter" as one of these choices but we could also call it something else entirely, at your choosing

<img width="420" alt="Screen Shot 2020-09-10 at 10 31 40 AM" src="https://user-images.githubusercontent.com/13387561/92745991-d71a9c00-f350-11ea-99ee-8a572f149625.png">

3. Any particular way you would like to be credited or linked beyond a link to here and to discodsp in our manual, changeling, and so forth?

Thanks so much for your time!

**Comment by reales** [comment]
Hello,

1. I don't see any issues.

2. OB-Xd filter seems a nice naming choice.

Cheers,
George.

**Comment by baconpaul** [comment]
Thank you! I’ll close this issue and post here if I get it working in a nightly 

Best
