### ISSUE TITLE
StudioRack integration

### ISSUE THREAD

**Issue by kmturley** [reales/OB-Xd#38]
I'm the lead developer of an open-source VST plugin manager called StudioRack:
https://github.com/studiorack

The aim of my project is to provide a free open-source way to manage VST plugin dependencies and their versions. I would love to add OB-Xd to the StudioRack Registry, which would involve the following steps:

1. Publish a Github release containing the plugin source along with metadata plugins.json
2. Tag your Github repository with studiorack-plugin so it can be discovered
3. Wait for the studiorack-registry to index your plugin (every 24 hours)
4. Check the registry feed for your plugin to appear https://studiorack.github.io/studiorack-registry/

Wondering if you would be interested in collaborating to make this work? It would then allow users to install OB-Xd using the StudioRack website, command-line tool or app?

Thanks!

**Comment by reales** [comment]
I'd need details about how to generate a proper metadata plugins.json

**Comment by kmturley** [comment]
I've got full instructions here:
https://studiorack.github.io/studiorack-site/docs/05-develop-new-plugins

Should be pretty easy, you can either use the studiorack/cli tool or generate it yourself!

**Comment by reales** [comment]
There's currently no time to implement this request but anyone else is welcome to contribute.
