### ISSUE TITLE
Make README more explicit about different versions

### ISSUE THREAD

**Issue by josephernest** [reales/OB-Xd#4]
Is https://obxd.wordpress.com/ maintained by the author of https://github.com/reales/OB-Xd or the author of https://github.com/2DaT/Obxd?

Here: https://www.kvraudio.com/product/ob-xd---virtual-analog-synthesizer-by-discodsp seems to be a "discoDSP" version.

It could be interesting for users to make the README more explicit about:

* the 2DaT version  (link to VST .dll file?)
* the reales version (link to VST .dll file or installer?)
* the discoDSP version?

**Comment by reales** [comment]
reales / discoDSP is based on 2Dat with GUI enhancement additions. Wordpress is not maintained by discoDSP only https://www.discodsp.com/obxd/

**Comment by josephernest** [comment]
Thank you for these informations.
