### ISSUE TITLE
[Q] libcurl-gnutls dependency

### ISSUE THREAD

**Issue by biopsin** [reales/OB-Xd#46]
Hi,
I was wondering if it's possible to drop the dependency on libcurl-gnutls.so ?
Problem it's called something else on my system and I see no perticular reason why 
this plugin depends on it anyways.

**Comment by reales** [comment]
What's the system?

**Comment by biopsin** [comment]
:voidlinux

```
$ mlocate libcurl
/usr/lib/libcurl.so.4
/usr/lib/libcurl.so.4.7.0

$ ldd OB-Xd.so
        linux-vdso.so.1 (0x00007ffcf91d2000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f141e668000)
        libcurl-gnutls.so.4 => not found
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f141e65d000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f141e658000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f141e637000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f141e3c1000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f141e27a000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f141e260000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f141e09c000)
        libbz2.so.1 => /usr/lib/libbz2.so.1 (0x00007f141e089000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f141e050000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f141de39000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f141ef1d000)

```
also the DAW is not connected to the web, so whatever it needs to pull it won't reach it..

**Comment by reales** [comment]
Checked JUCE_WEB_BROWSER and it's disabled. No idea where libcurl dependency comes from.

**Comment by biopsin** [comment]
Well did some lookin around and found this thread 
https://forum.juce.com/t/minimise-dependencies-do-i-really-need-libcurl/27696#

Seems libcurl is now a juce_core dependency and can not be disabled and the non-libcurl linux code is depricated.

> However, if you add the linker flag -Wl,--as-needed then you will only need libcurl when building your JUCE app (install the libcurl-dev packages) but your JUCE app will not depend on it at runtime if you do not use any networking functions.

**Comment by reales** [comment]
Thanks for pointing up. JUCE_USE_CURL has been disabled in juce_core module and binaries have been compiled again. It should fix the issue. Linux build can be downloaded at https://www.discodsp.com/download/?id=9
