### ISSUE TITLE
Install failed, cant write to Documents folder

### ISSUE THREAD

**Issue by agung-wete** [reales/OB-Xd#47]
Hi

![2021-01-28_05-13-51](https://user-images.githubusercontent.com/4055492/106093408-cda89980-6162-11eb-97ea-2413f1284305.png)

Using Ver 2.2.
It also happened for other file in that folder (themes etc)

Tried using admin mode, also manual delete. But still wont work

Thank you

**Comment by reales** [comment]
Looks like Documents > discoDSP > OB-Xd has some write permission issues. Try deleting the OB-Xd folder first and try again.

**Comment by agung-wete** [comment]
> Looks like Documents > discoDSP > OB-Xd has some write permission issues.
> Try deleting the OB-Xd folder first and try again.

hi, deleted the folder but error still persist

**Comment by agung-wete** [comment]
Sorry, my bad. I disabled the antivirus and its works
