### ISSUE TITLE
Do Program Changes work with VST3?

### ISSUE THREAD

**Issue by mkruselj** [reales/OB-Xd#48]
I have tried in Reaper 6, FL Studio 20 and Bitwig 3, all latest versions, and I couldn't make program changes work with the latest OB-Xd nightly by simply changing the program change value (using ReaControlMIDI in Reaper, MIDI Out in FL20, and MIDI Program Change note FX in Bitwig).

Is this something on JUCE side, or individual host side, or...?

**Comment by reales** [comment]
It should work using the regular MIDI messages http://midi.teragonaudio.com/tech/midispec/pgm.htm

**Comment by mkruselj** [comment]
Yeah, I'm sending them but OB-Xd doesn't switch programs... Works with OB-Xd VST2 (of course).

**Comment by reales** [comment]
Maybe it’s related to VST3 and JUCE. Will check.

**Comment by mkruselj** [comment]
Here's what one of Reaper developers said:

"Sending program change messages fails for that plugin because it returns kNotImplemented from IUnitInfo::getUnitByBus, which is meant to tell us that the plugin can accept program change messages on a given MIDI bus/channel. If we skip that call and just assume the plugin can accept messages on any MIDI channel, it does process the program change messages. "

https://forum.cockos.com/showthread.php?t=251104

**Comment by reales** [comment]
Thanks for taking the time investigating the issue. A fix is very likely to be coming very soon.

**Comment by mkruselj** [comment]
Great! 🙂

**Comment by mkruselj** [comment]
@reales The latest Reaper dev build (625+dev0322) does work with current nightly of OB-Xd regarding program changes (they did what was mentioned above, skipped that call and assumed plugin accepts prog changes on any MIDI channel).

Just letting you know, Reaper is fine now. Other DAWs, though... :slightly_smiling_face: So I will retest this with all DAWs that I have whenever you have a new nightly up!

**Comment by reales** [comment]
Check https://forums.steinberg.net/t/no-program-changes-in-vst3-regrettable-decision/122202

**Comment by mkruselj** [comment]
Yeah I remember reading that some time ago, but what does this mean for OB-Xd (or I guess program change support in VST3 under JUCE in general)?

**Comment by reales** [comment]
I think it's related to JUCE and VST3 https://forum.juce.com/t/midi-program-change-broken-solved/32266/2

**Comment by mkruselj** [comment]
Hmm. So, no fix incoming then? :slightly_frowning_face:

**Comment by reales** [comment]
We have some tweaks that may fix it. Will be ready on the next nightly.

**Comment by mkruselj** [comment]
OK cool - eager to test it out here!
