### ISSUE TITLE
new sources are missing in .jucer

### ISSUE THREAD

**Issue by KottV** [reales/OB-Xd#50]
Hi,

Looks like .jucer (in master) was not updated for recent additions. It needs SetPresetNameWindow.cpp SetPresetNameWindow.h.

**Comment by plaimbock** [comment]
Can confirm. On Fedora34 with GCC11 I see this error:

...
mkdir -p build
g++ -o build/OB-Xd.so build/intermediate/Release64/include_juce_audio_plugin_client_VST2_dd551e08.o  build/OB-Xd.a -m64 -Lbuild -Lbuild -L/usr/X11R6/lib/ -lasound -lfreetype -lcurl  -fvisibility=hidden -no-pie -lrt -ldl -lpthread -lGL  -shared -Wl,--no-undefined  -m64
/usr/bin/ld: build/OB-Xd.a(PluginEditor_94d4fb09.o): in function `ObxdAudioProcessorEditor::MenuActionCallback(int)':
PluginEditor.cpp:(.text+0x56aa): undefined reference to `SetPresetNameWindow::SetPresetNameWindow()'
/usr/bin/ld: PluginEditor.cpp:(.text+0x59f9): undefined reference to `SetPresetNameWindow::SetPresetNameWindow()'
/usr/bin/ld: PluginEditor.cpp:(.text+0x5792): undefined reference to `SetPresetNameWindow::grabTextEditorFocus()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:157: build/OB-Xd.so] Error 1

**Comment by reales** [comment]
Fixed on https://github.com/reales/OB-Xd/commit/aef7d8a5ca211fa1b24c259899d756b0a696a71f
