### ISSUE TITLE
Preset Dropdown on VST2 No Longer Working (Ableton Live)

### ISSUE THREAD

**Issue by zcklip** [reales/OB-Xd#53]
With the latest update of OB-Xd, the native dropdown to select different presets/programs in Ableton Live no longer works. The presets/programs listed don't change with a bank switch, and selecting a preset via the dropdown seems to change the parameters, but the plugin still shows the default preset as the one selected. Here are some screenshots that show the problem:

When the preset is selected inside OB-Xd:
![Screenshot 2021-05-13 224632](https://user-images.githubusercontent.com/83312839/118214242-6080f180-b43d-11eb-947e-fdb6fcffb1a9.png)

When the preset is selected via the Ableton dropdown menu:
![Screenshot 2021-05-13 224810](https://user-images.githubusercontent.com/83312839/118214371-97570780-b43d-11eb-9a74-0edc5c87c721.png)

**Comment by reales** [comment]
The issue may be related to the DAW itself. We implemented some workaround on the latest nightly https://www.discodsp.net/obxd-nightly/
