### ISSUE TITLE
Voice Variation is silent

### ISSUE THREAD

**Issue by benwiley4000** [reales/OB-Xd#54]
I have to admit I don't understand the Voice Variation section too much as this is app is my closest experience to the OB-X, but I did notice a bug with several patches where only every other midi note press would trigger sound. Then I realized this was due to voices with "voice variation" turned on being silent. By rolling back the variation on all the voices, all my note presses are now audible.

I'm running the iPad version.

**Comment by reales** [comment]
Please point a specific preset having such issue.

**Comment by benwiley4000** [comment]
The 1998 preset has this issue.

**Comment by reales** [comment]
Can't find the preset.
