### ISSUE TITLE
Exporting/saving preset crashes app

### ISSUE THREAD

**Issue by benwiley4000** [reales/OB-Xd#55]
When I went to hit "export preset" the app immediately crashed. When I hit "save preset" it didn't immediately crash but after a few seconds the UI froze and I never was able to find the preset anywhere. Note that I'm using the "blank canvas" bank that I downloaded from this repository as it wasn't available in the app. In general it's not clear how I'm supposed to manage custom presets without overwriting the ones that are there already. I'm using the iPad version.

**Comment by reales** [comment]
Looks like blank canvas is having issues after being imported to OB-Xd. Try using a different one meanwhile we address the issue.

**Comment by reales** [comment]
Fixed on the incoming 1.8 update.

**Comment by benwiley4000** [comment]
Thank you!
