### ISSUE TITLE
Allow portable install

### ISSUE THREAD

**Issue by m-camilleri** [reales/OB-Xd#59]
As pointed out [here](https://github.com/reales/OB-Xd/issues/5?_pjax=%23js-repo-pjax-container) it would be great if OB-Xd allowed portable installs like DEXED.

**Comment by reales** [comment]
If you're in a heavy need, simple modify line 776 from PluginProcessor.cpp

File folder = File::getSpecialLocation(File::userDocumentsDirectory).getChildFile("discoDSP").getChildFile("OB-Xd");

To your preferred location and compile.
