### ISSUE TITLE
Compiling v2.8 with JUCE 6.1.6 in Ubuntu 22.04 fails (fix included)

### ISSUE THREAD

**Issue by gitterdude** [reales/OB-Xd#69]
When I try to compile v2.8, aka commit 025eed312cab8592fe0877a81904d9abcca71bc2, I get

_Compiling PresetBar.cpp
In file included from ../../Source/Components/../PluginProcessor.h:28,
                 from ../../Source/Components/ScaleComponent.cpp:10:
../../Source/Components/../../JuceLibraryCode/JuceHeader.h:17:10: fatal error: juce_audio_basics/juce_audio_basics.h: No such file or directory
   17 | #include <juce_audio_basics/juce_audio_basics.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
../../JuceLibraryCode/include_juce_audio_plugin_client_VST3.cpp:9:10: fatal error: juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp: No such file or directory
    9 | #include <juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp>_

The solution is to run
```
sed -i 's/useLocalCopy="0"/useLocalCopy="1"/' OB-Xd.jucer
sed -i 's/JUCE_USE_CURL="0"/JUCE_USE_CURL="0" JUCE_VST3_CAN_REPLACE_VST2="0"/' OB-Xd.jucer
```
prior to running Projucer

The second sed is to keep it from complaining about

_Compiling SetPresetNameWindow.cpp
In file included from ../../JuceLibraryCode/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp:26,
                 from ../../JuceLibraryCode/include_juce_audio_plugin_client_VST3.cpp:9:
../../JuceLibraryCode/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:68:11: fatal error: pluginterfaces/vst2.x/vstfxstore.h: No such file or directory
   68 |  #include "pluginterfaces/vst2.x/vstfxstore.h"_

even though I unchecked "VST (Legacy)" in Projucer
It's needed due to the closed but incorrectly fixed issue  #40 : "Linux VST3 build still requires VST2 headers"

**Comment by reales** [comment]
Haven't tried with Ubuntu 22 yet but had no compiler issues with Ubuntu 20.04 LTS.

Will check, thanks.

**Comment by gitterdude** [comment]
I had the same issues in 20.04 and the sed lines solved it there as well.

The JUCE_VST3_CAN_REPLACE_VST2="0" line was suggested in issue #40  , and you seem to have added it at one point but with the incorrect value "1", but that line appears to have been removed in subsequent commits.

**Comment by gitterdude** [comment]
"JUCE_VST3_CAN_REPLACE_VST2=1" appears to be a legacy, compatibility setting so changing it to 0 seems to be the way forward. Maybe for a 3.0 release, to make clear that there may be compatibility issues.

I found some discussions regarding it here https://forum.juce.com/t/juce-5-4-1-and-vst3/30398/5

Another way to do it would be if that setting could be changed when one unchecks VST (Legacy). I don't know if that's possible.

Yes, I unchecked VST (Legacy) before saving in Projucer.

**Comment by reales** [comment]
Have you tried compiling using VST2 SDK?

**Comment by gitterdude** [comment]
No, but I don't think using a technology that Steinberg deprecated in 2018 and discontinued in January this year should be a default requirement.

To be fair; for my own builds of OB-Xd I'm using a few files and instructions from Odin 2, along with the sed lines above and a few other fixes, to compile a LV2 version.
LV2 is still the preferred plugin format for Linux, AFAIK.

This was more of a hint to people who want to compile a VST3 version of OB-Xd but don't want to try and find a discontinued SDK first.

**Comment by reales** [comment]
All good, thanks for your contribution.
