### ISSUE TITLE
LV2 is not working

### ISSUE THREAD

**Issue by KottV** [reales/OB-Xd#73]
Hi, 
LV2 build doesn't produce any sound. I think it's a bug in JUCE when you have any `pluginChannelConfigs="` set: https://forum.juce.com/t/juce7-technical-preview-branch/50866/183?u=kottvv

I f you rebuild plugin without channel config, then it will work.

**Comment by reales** [comment]
I'm getting the following error compiling LV2 without channel config {0,2}

`make: *** [Makefile:114: build/OB-Xd.lv2/OB-Xd.so] Error 1`

[OB-Xd LV2.jucer.zip](https://github.com/reales/OB-Xd/files/9181534/OB-Xd.LV2.jucer.zip)
[Makefile.zip](https://github.com/reales/OB-Xd/files/9181540/Makefile.zip)

**Comment by KottV** [comment]
>Be aware that if Enable copy plugin step gets disabled it won't compile.

yeah, another bug in Projucer export

**Comment by reales** [comment]
I'll leave the issue open until JUCE team fixes the channel issue, hopefully with an incoming release soon.
