### ISSUE TITLE
Possible to add my own sample sounds ?

### ISSUE THREAD

**Issue by titus-shoats** [reales/OB-Xd#74]
Hello im in love with this vst, I would like to know is it possible to add my own sounds/samples to this vst using JUCE SamplerSound class. Im interested in modifying the vst to add my own samples but I'm not sure how.  There has to be a way to add a sample to the audio source, and still be able to use all of the modular effects etc.  Can anyone point me in the right direction please..

**Comment by reales** [comment]
Yes, it would be possible, however the main engine and GUI will require some heavy work on it.

**Comment by titus-shoats** [comment]
Thanks for your reply, which class within this vst would I need to look in or modify to subclass JUCE's SamplerSound, or  SamplerVoice() to add my own sounds/sample?

**Comment by reales** [comment]
I have no knowledge of those JUCE functions, sorry.
