### ISSUE TITLE
No Sound as VST and LV2-Plugin OB-XD V.2.9 in Ardour7 and Carla with Pipewire

### ISSUE THREAD

**Issue by Pergravis** [reales/OB-Xd#75]
Hello,
I have no sound output under Ardour7 and Carla with the OB-Xd 2.9 LV2 and VST plugin.
I use the latest arch version with RT kernel LTS and Pipewire.
All other LV2 instruments plugins work.
How can I create a debug log for you?
Greetings

**Comment by reales** [comment]
Hello, Release 2.9 was compiled with JUCE 7.0.1 which had some problems with LV2 channel config. I’ll compile 2.10 with 7.0.2 in the coming days to see if it fixes this issue.

**Comment by Pergravis** [comment]
Thank you!

**Comment by reales** [comment]
2.10 is out now with JUCE 7.0.2 framework update, please give it a try.

**Comment by reales** [comment]
Closing this report due to lack of feedback and will open a new issue regarding LV2 and Linux.
