### ISSUE TITLE
LV2 Linux plugin not loading properly due to JUCE channel config

### ISSUE THREAD

**Issue by reales** [reales/OB-Xd#78]
Based on reports, it looks like JUCE doesn't like the current {0,2} channel config.

Please the build below compiled with JUCE 7.0.2 and no channel config will be uploaded for review and feedback.

[OB-Xd.lv2.zip](https://github.com/reales/OB-Xd/files/9970355/OB-Xd.lv2.zip)

**Comment by KottV** [comment]
Archive doesn't have any .ttl files, so it won't work. Could you show the .jucer for that build?

Also, bug was fixed in https://github.com/juce-framework/JUCE/commit/7ebd34012cb81f1cdece5c34da2eb8f83d829085 after 7.0.2 release.

**Comment by reales** [comment]
Right, I deleted Bin and Builds folders and compiled again and it should work now.

Find the new build below plus the requested Linux LV2 jucer project.

[OB-Xd LV2.jucer.zip](https://github.com/reales/OB-Xd/files/9974068/OB-Xd.LV2.jucer.zip)
[OB-Xd.lv2.zip](https://github.com/reales/OB-Xd/files/9974069/OB-Xd.lv2.zip)

**Comment by reales** [comment]
Closing the issue since 7.0.3 should fix this and OB-Xd 2.11 will be compiled with it or a higher build.
> 
> Also, bug was fixed in [juce-framework/JUCE@7ebd340](https://github.com/juce-framework/JUCE/commit/7ebd34012cb81f1cdece5c34da2eb8f83d829085) after 7.0.2 release.
