### ISSUE TITLE
No Sound in lv2-Version

### ISSUE THREAD

**Issue by ShantySuffisance** [reales/OB-Xd#80]
Thank you very much for that great synth! 

I compiled v2.10 with juce-7.0.2-linux. Sound is working in vst3-Version and in Standalone but not in lv2. The plugins were loaded in Carla v2.5.0 with jack2 v1.9.22 on Ubuntu 18.04.6 LTS x86_64. 

It's not a problem for me, just wanted to let you know.

**Comment by reales** [comment]
JUCE 7.0.2 has issues with LV2 plugins. Please try this new 2.11 build compiled using JUCE 7.0.3 and report back.

[OB-Xd.lv2.zip](https://github.com/reales/OB-Xd/files/10200729/OB-Xd.lv2.zip)

**Comment by reales** [comment]
The issue has been fixed on developer branch updated to be compiled with JUCE 7.0.3.

I'm attaching a nightly LV2 build verified to work with Carla 2.1 as LV2 and Ubuntu 18 LTS.

[OB-Xd.lv2.zip](https://github.com/reales/OB-Xd/files/10216534/OB-Xd.lv2.zip)

**Comment by ShantySuffisance** [comment]
Thank you very much!
I confirm that sound works with JUCE 7.0.3.
